### PR TITLE
Key chain/ key store based implementation

### PR DESCRIPTION
**Pull request by brucewilkins**
Hi

Love your library, especially all the work that's gone into the Android side of things.

For a project I'm working on I need key chain based fingerprint authentication along with the requirement to securely store user credentials for iOS and Android.

It seems like this would be a good addition to your library rather than duplicating the logic to check fingerprint status and all the Android fingerprint logic, what do you think?

This pull request contains an iOS implementation, with stubs for the other platforms, as well as an addition to the sample project. I'll be working on the Android implementation for my project in the coming weeks. If you have any tweaks to the interface or other suggestions le me know and I can make the necessary adjustments.

Let me know if you are happy for me to collaborate on it.

### CODE REVIEW

**Comment by smstuebe** [comment]
> It seems like this would be a good addition to your library rather than duplicating the logic to check fingerprint status and all the Android fingerprint logic, what do you think?

Yes, totally! It was in my mind since I started the plugin. See: #3 :D

Actually I was starting the implementation locally. Thanks for the PR. I'll have a look at it and may use it as a starting point or the complete implementation :)

**Comment by smstuebe** [comment]
oups wrong version :D was confused by the BLE plugin version. ^^ Now it's on 1.5.0

**Comment by brucewilkins** [comment]
Nice!

Any thoughts or comments on the interface structure or naming? 

Going to pick up the Android implementation in the coming two weeks or so. There might need to be some additional configuration due to the way Android key store works. Let me know if you have any preferences regarding this.

**Comment by smstuebe** [comment]
Hmm I wanted to learn something about the Android stuff as well (Easterhack ^^). I'm not sure if how to prevent double effort here.

**Comment by brucewilkins** [comment]
No worries if you want to look into it this weekend. I'll check with you before I do anything. 
As far as I can tell, the Android implementation is going to be a lot more work; it will involve creating a public/ private key in the KeyStore first which iOS does behind the scenes.

Lets keep in touch!

**Comment by brucewilkins** [comment]
Hey Sven-MichaelHow was your Easter weekend?Just wondering what your latest update is on the Android keystone implementation. Regards, Bruce.On 10 Apr 2017 8:26 PM, Bruce WILKINS <zabrucewayne@yahoo.com> wrote:No worries if you want to look into it this weekend. I'll check with you before I do anything. As far as I can tell, the Android implementation is going to be a lot more work; it will involve creating a public/ private key in the KeyStore first which iOS does behind the scenes.Lets keep in touch!       From: Sven-Michael Stübe <notifications@github.com> To: smstuebe/xamarin-fingerprint <xamarin-fingerprint@noreply.github.com> Cc: Bruce Wilkins <zabrucewayne@yahoo.com>; Author <author@noreply.github.com> Sent: Monday, 10 April 2017, 10:35 Subject: Re: [smstuebe/xamarin-fingerprint] Key chain/ key store based implementation (#56)   Hmm I wanted to learn something about the Android stuff as well (Easterhack ^^). I'm not sure if how to prevent double effort here.

**Pull request merged**
