### PR TITLE
Android fallback authentication (PIN/pattern/password)

### PR DESCRIPTION
**Pull request by k-shan**
Hey,

Great plugin, I've implemented android fallback authentication in this PR to mimic iOS fallback auth. I realize a there may be some overlap with some contributions on the 1.5.0 branch.

Let me know your thoughts,

### CODE REVIEW

**Comment by CarbonSft** [comment]
Hi @smstuebe. Can we have this improvement merged? 
Thank you in advance.

**Comment by smstuebe** [comment]
@CarbonSft had no time to look it up. I'll have a look after some bugfixes. I plan a bigger release end of this year (see Milestone 1.5 https://github.com/smstuebe/xamarin-fingerprint/milestone/2 ) Depending on my free time, it will be earlier.

**Comment by galadril** [comment]
+1
Any progress on the 1.5.0 version?

**Comment by smstuebe** [comment]
@galadril do you want to write a comment under each issue? I have a job and don't want to lose my CS:GO skill. So yes there is progress, yes I will merge the other stuff. 🙄

**Comment by galadril** [comment]
@smstuebe sry man, won't comment anymore 🥇

**Comment by Im-PJ** [comment]
Scared to ask but any thoughts to merge this?

**Comment by smstuebe** [comment]
@Im-PJ yes it will, sorry :( Can you remotely uninstall CS:GO from my dev machine, please ^^ I'm really sorry for not merging 😞

**Comment by dushani88** [comment]
Hi @Im-PJ, when will this be available?

**Comment by Im-PJ** [comment]
You are scared to ask @smstuebe so you are asking me. Nice try.

**Comment by joshykautz** [comment]
@Im-PJ Any word? 😂

**Comment by smstuebe** [comment]
It's in the current pre release. Give it a try if you are brave enough #151 
The fallback is now covered by googles BiometricPrompt androidx impementation.

**Pull request closed without merging**
